### ISSUE TITLE
Error in tutorial for near.academy/near101/chapter-6 

### ISSUE THREAD

**Issue by CloudCodeCraft** [NEAR-Edu/near.academy#11]
[https://near.academy/near101/chapter-6](https://near.academy/near101/chapter-6)

there's a bug at this above page.

it asks you to do this contract call with the NPM command line tool:

```bash
near call museum.testnet add_meme \
'{"meme" : "bob", "title" : "god", "data" : "https://9gag.com/gag/ad8K0vj", "category" : 4}' \
--accountId YOUR_ACCOUNT_NAME.testnet --amount 3
```

HOWEVER:

this contract will always run out of gas no matter what values you put in the call.

this is how the error message looks likes:

![unknown](https://user-images.githubusercontent.com/87612696/152633091-2e6bbd07-4460-47b8-8ca3-61d211dc75ff.png)

and it seems I am not the only one to have this problem because in the block explorer

(observe the failure calls for the `add_meme` method for the `museum.testnet` smart contract)

![unknown](https://user-images.githubusercontent.com/87612696/152633115-edbc3c37-b04e-4252-9b5c-1dfe8dc0c0cc.png)

**Comment by DannySLee1996** [comment]
just noticed a PR has been put for this:

https://github.com/NEAR-Edu/near.academy/pull/10

**Comment by ryancwalsh** [comment]
@daniel-lee-tech Thank you so much for bringing this back to my attention. I will look at the PR.
