### ISSUE TITLE
cursor is accidentally jumping around in ChapterView

### ISSUE THREAD

**Issue by frolovdev** [NEAR-Edu/near.academy#12]
**Describe the bug**
the cursor is accidentally jumping around, look at the video

**To Reproduce**
1. Just try to write things down a little bit faster than you do

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
<img width="506" alt="image" src="https://user-images.githubusercontent.com/30667180/153728177-e7718de0-2e4e-42b0-87bd-bb28d41477ef.png">

Chrome last version

**Additional context**

Here's the vid
https://vimeo.com/676656735

**Comment by ryancwalsh** [comment]
Thanks for sharing this video. It looks like you're using Chrome on Mac. I'll look into this when I get a moment.

**Comment by ryancwalsh** [comment]
@encody If this is an easy fix, great. Otherwise, it's probably not affecting that many people, and we don't need to prioritize it.

**Comment by encody** [comment]
This appears to be caused by the chapter module updating the `value` of the monaco editor component, which in turn refreshes/reloads the editor, apparently resetting the cursor position as well. Essentially, the chapter module is not using the monaco editor quite how it was intended to be used.
