### ISSUE TITLE
Sign-up not working

### ISSUE THREAD

**Issue by alexsomai** [NEAR-Edu/near.academy#13]
**Describe the bug**
I cannot sign-up on https://near.academy/sign-up

**To Reproduce**
1. Go to https://near.academy/sign-up
2. Complete the fields
3. Press the Sign Up button
4. Nothing happens

**Expected behavior**
Sign up should work.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome
 - Version 98

**Additional context**

CORS error seem to appear in the Console tab

> Access to fetch at 'https://api.near.academy/user/sign-up' from origin 'https://near.academy' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by ryancwalsh** [comment]
Thank you for reporting this! We are trying to move this website to a different server and thought the transition would be faster and smoother. We're working now to either finish the transition or revert back to where it was. Thanks.

**Comment by oceanByte** [comment]
Fixed with https://github.com/NEAR-Edu/near.academy/commit/dc01d6b55459d0f331f1c8be3a418bcbce2baaaa
