### ISSUE TITLE
Use `main` instead of `development` branch

### ISSUE THREAD

**Issue by ryancwalsh** [NEAR-Edu/near.academy#15]
After https://github.com/NEAR-Edu/near.academy/pull/14, update https://dashboard.render.com/web/srv-c81d0hbvog4kd0lhropg/settings and https://dashboard.render.com/web/srv-c81d23rvog4kd0lhrqrg/settings to use "main" instead of "development".

**Comment by oceanByte** [comment]
#14 was merged and settings can be updated now.

**Comment by ryancwalsh** [comment]
Great. Updated. Thanks.
