### ISSUE TITLE
Point https://near.academy and subdomains to new server (probably Render.com)

### ISSUE THREAD

**Issue by ryancwalsh** [NEAR-Edu/near.academy#17]
Once our new server is working, we need to update the domains.

**Comment by oceanByte** [comment]
Great! Can you share where to point to, @ryancwalsh?

**Comment by ryancwalsh** [comment]
@oceanByte  https://near-academy-frontend-tfyr.onrender.com and https://near-academy-api.onrender.com are the URLs, but I tried signing up there at that frontend URL, and it didn't work. So I'm investigating. 

Definitely don't change the domain yet. There might be some more kinks to work out.

Thanks for all of your help today! 🎉💪

**Comment by ryancwalsh** [comment]
@oceanByte I was about to say that you can go ahead and point the subdomains to the onrender URLs mentioned above, but then it occurred to me: if it's the case that NEAR Foundation is supposed to own the actual near.academy domain at this point, it probably makes more sense for you to do a full transfer of that domain to whoever @amgando 's preferred registrar is.

Then from there, Sherif can point that domain to these onrender URLs.

I'll ask Sherif.

**Comment by ryancwalsh** [comment]
@oceanByte you can go ahead and point the subdomains to the onrender URLs mentioned above and then do a quick test to make sure that signup works, etc.

Then later this month when he has time, @amgando will work with you to do a transfer of the domain from your registrar to his. Thanks!

**Comment by ryancwalsh** [comment]
@oceanByte Are you still waiting on your teammate's help with this? Thanks!

**Comment by oceanByte** [comment]
I have access to the domain provider now and talked to @amgando. I will transfer the domain once we have finalized all changes here. 

I could point to the new URLs, but there is still an issue with the react-router on renderer.com. This should be resolved first, or we would not be able to share links beyond `near.academy/`

See a quick explanation and suggested solution here: https://stackoverflow.com/a/66261835

Let me know if this works or if you need any support here @ryancwalsh

**Comment by oceanByte** [comment]
Hi @ryancwalsh, I put the app to maintenance for about an hour and prepared all steps to finalize the transfer. We need to add the custom domain to the renderer apps though as well. See this https://render.com/docs/custom-domains#adding-a-custom-domain. Let me know when done and I'll proceed with the redirect.

**Comment by oceanByte** [comment]
Transfer completed. Domains are pointing to the renderer instances now.
