### ISSUE TITLE
Copying anything else that 101labs controls

### ISSUE THREAD

**Issue by ryancwalsh** [NEAR-Edu/near.academy#20]
The repo has multiple dependencies (examples: https://github.com/NEAR-Edu/near.academy/blob/2d347cb43088c88959b658c065319566f1bb57e1/src/frontend/package.json#L11 and https://github.com/NEAR-Edu/near.academy/blob/2d347cb43088c88959b658c065319566f1bb57e1/src/api/package.json#L11) mentioning labs101 and/or digitalocean.

We need to have copies (that we control) of any of that type of thing.

How can we do that?

**Comment by oceanByte** [comment]
> The repo has multiple dependencies

These are app names for Digital Ocean. We can delete these scripts if you plan to deploy to a different service or just rename them to the name of your app names on Digital Ocean.

**Comment by oceanByte** [comment]
Fixed with https://github.com/NEAR-Edu/near.academy/pull/24.
