### ISSUE TITLE
Migrate CloudFlare account to one that NEAR Foundation owns

### ISSUE THREAD

**Issue by ryancwalsh** [NEAR-Edu/near.academy#22]
https://www.cloudflare.com/

**Comment by ryancwalsh** [comment]
@oceanByte I created a free account at https://dash.cloudflare.com/d03a6379324922b1c8265bb604f3d8b7/near.academy/dns but haven't done anything with it yet.  If there are steps I can take asynchronously to help with this migration, just let me know.

Otherwise we can schedule: https://calendly.com/ryan-walsh-near/

**Comment by ryancwalsh** [comment]
@oceanByte Can you please let me know how I can help move this along?

**Comment by oceanByte** [comment]
Consider this specific task done. We need to fix the react-router bug on Renderer and then I will point the domain to your Cloudflare instance and this will point to Renderer.

**Comment by ryancwalsh** [comment]
https://ap.www.namecheap.com/domains/domaincontrolpanel/near.academy/domain Nameservers now point to the ones that https://dash.cloudflare.com/d03a6379324922b1c8265bb604f3d8b7/near.academy instructs

https://dash.cloudflare.com/d03a6379324922b1c8265bb604f3d8b7/near.academy/ssl-tls
"Your SSL/TLS encryption mode is Full" (as Albert instructed)

I looked at https://render.com/docs/configure-cloudflare-dns

https://dash.cloudflare.com/d03a6379324922b1c8265bb604f3d8b7/near.academy/dns now has only 2 rows: CNAMEs pointing to `near.academy` and `api` (for their respective onrender URLs).

I tested logging out and back in at https://near.academy/ and everything seems to be working fine.
