### ISSUE TITLE
important formatting problems lead to confusion

### ISSUE THREAD

**Issue by ryancwalsh** [NEAR-Edu/near.academy#29]
Notice how words like `assert_contract_is_initialized()` get changed to `assertcontractis_initialized()`.

This is super confusing for new people.

![image](https://user-images.githubusercontent.com/2086493/156448789-4278d39c-8ad9-4955-a30f-ee53f235dca7.png)

https://near.academy/near101/chapter-6 is just one example.

We need to diagnose why this is happening and fix it throughout the whole site.

**Comment by oceanByte** [comment]
It happens, because it gets rendered as markdown. So `_get_vote_score_` will be rendered in italic.  You need to escape all Markdown syntax like `\_get_vote_score\_` or disable markdown rendering altogether.

**Comment by ryancwalsh** [comment]
Thanks, @oceanByte !
