### ISSUE TITLE
Visiting paths (such as `/sign-up`) directly shows "Not Found"

### ISSUE THREAD

**Issue by ryancwalsh** [NEAR-Edu/near.academy#31]
As I mentioned at the bottom of my comment https://github.com/NEAR-Edu/near.academy/issues/25#issuecomment-1054635717 and as @oceanByte mentioned at https://github.com/NEAR-Edu/near.academy/issues/17#issuecomment-1057450569:

https://near-academy-frontend-tfyr.onrender.com/sign-up (if I visit it directly) shows `Not Found` but if I visit https://near-academy-frontend-tfyr.onrender.com and _then_ click Sign Up, the page loads fine. That direct route works fine at https://near.academy/sign-up (on your old server).

My guess is that the original near.academy on Digital Ocean fixed this problem via some outside-of-this-repo config such as `.htaccess` file.

We can explore suggestions at https://stackoverflow.com/a/36623117/470749 and elsewhere.

**Comment by ryancwalsh** [comment]
I think we should try starting with the catch-all approach suggested in that StackOverflow answer.

**Comment by ryancwalsh** [comment]
@oceanByte Thanks for following up on this!! :-)

My sense is that you recommend that we fix this issue before completing the migration to Render.com because if you switch the domain to point to our site (hosted on Render) and people start trying to visit URLs of direct pages, it would cause a lot of confusion and hassle.  

That makes sense to me.

@petarvujovic98 Is brand new on the team and has this issue on his mind and has already investigated a bit and might be able to look at this issue more tomorrow if he's not swamped with other onboarding tasks.

**Comment by petarvujovic98** [comment]
@ryancwalsh I looked into this and found Render docs which address this exact issue [here](https://render.com/docs/deploy-create-react-app#using-client-side-routing). 

I added the necessary rule to the deployment on Render and it seems to be doing exactly what we want it to.

I think we can close this as soon as you have a look at it.

**Comment by ryancwalsh** [comment]
@petarvujovic98 Wow! Great find! 

~ ~ ~

@oceanByte I'll close this ticket now because it does seem solved to me since https://near-academy-frontend-tfyr.onrender.com/sign-up works (but let me know if you know of any other related problem).

I think this means you're clear to proceed with https://github.com/NEAR-Edu/near.academy/issues/17#issuecomment-1057450569 now?
